### ISSUE TITLE
VsixTesting doesn't work with NCrunch

### ISSUE THREAD

**Issue by jcansdale** [josetr/VsixTesting#10]
It appears `VsixTesting` doesn't currently work with NCrunch. 😢 

![image](https://user-images.githubusercontent.com/11719160/44905908-607f4880-ad0b-11e8-8092-ab89dd237110.png)

It seems the issue is the `TestFramework` attribute:
```
[assembly: TestFramework("Xunit.VsTestFramework", "VsixTesting.Xunit")]
```

Even regular `[Fact]` tests aren't detected when a test project includes this attribute (see `ASimpleFact` above).

@remcomulder have you come across this issue before? Is there any way to get this working? 🙏

**Comment by jcansdale** [comment]
From @remcomulder  on twitter:

> Ahh, ok. It's completely replacing the Xunit test framework then.  As far as NCrunch is concerned, this is then an entirely new test framework that could have an entirely different reporting and integration structure. No way to support this without a deep dive and lots of effort

https://twitter.com/remcomulder/status/1035684665166680064

**Comment by jcansdale** [comment]
@sharwell Oh, interesting. What the the reason for the degradation? Did it need to fire up one instance of Visual Studio per test in the non-`[TestFramework]` version?

**Comment by sharwell** [comment]
Exceptions which resulted in a test failure would only get reported to the user if they were serializable. `XunitException` was one of the exception types which is not serializable.

**Comment by jcansdale** [comment]
> Exceptions which resulted in a test failure would only get reported to the user if they were serializable. XunitException was one of the exception types which is not serializable.

That does sound like a bit of a show stopper. 😢
