### ISSUE TITLE
Add option to launch Visual Studio from VsixTesting.ExtensionInstaller

### ISSUE THREAD

**Issue by jcansdale** [josetr/VsixTesting#14]
We've recently been struggling to keep the GitHub for Visual Studio extension working on both Visual Studio 2017 and 2015. The team now primarily uses 2017 and the extension is built with 2017. Installing, running and debugging on 2015 has become a pain.

I was wondering how feasible it would be to use various components of `VsixTesting` to create a painless F5 experience for installing and running extensions in different versions?

1. Add an option to launch Visual Studio from `VsixTesting.ExtensionInstaller` after installing
2. Use the debug propagation trick, so that if `VsixTesting.ExtensionInstaller` is started with the debugger attached, it would automatically attach the debugger from the parent `devenv` process to the child process

We could then create a `launchSettings.json` entry for the Visual Studio versions we want to target. It might be something like this:
```json
    "Start VS 2015": {
      "commandName": "Project",
      "commandLineArgs": "/ApplicationPath \"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\devenv.exe\" /RootSuffix Exp
            /InstallAndStart \"$(SolutionDir)build\\$(Configuration)\\GitHub.VisualStudio.vsix\""
    },
```

Do you think that would work?

**Comment by sharwell** [comment]
I once tried to resolve this, but the solution wasn't as stable as I liked. A launcher of some form would be great.

Do you know what happens if you Right Click &rarr; Debug Test from Test Explorer on the meta test intended to just launch VS 2015? Maybe it already does what you want?

**Comment by jcansdale** [comment]
> I once tried to resolve this, but the solution wasn't as stable as I liked, and it had a substantial build performance impact. A launcher of some form would be great.

I've always found it strange that the install component is part of build rather than run. I guess there's just more customization options with build compared to run.

> Do you know what happens if you Right Click → Debug Test from Test Explorer on the meta test intended to just launch VS 2015? Maybe it already does what you want?

That would be a killer feature if it did work! Alas the test seems to exit immediately and the test node vanishes. 😕

**Comment by sharwell** [comment]
You could create an asynchronous unit test that does this:

```
await new TaskCompletionSource<int>().Task;
```

😆

**Comment by josetr** [comment]
> > Do you know what happens if you Right Click → Debug Test from Test Explorer on the meta test intended to just launch VS 2015? Maybe it already does what you want?
> 
> That would be a killer feature if it did work! Alas the test seems to exit immediately and the test node vanishes. 😕

At the time it made sense that if the user selects 0 VsFact_/_VsTheory_ tests then no Visual Studio instance should be launched but I can make that work.

The only problem with both approaches is that 99% of the times you wouldn't be able to debug things like `Package.Initialize()` since they may run before `VisualStudioUtil.GetDte` finds the DTE instance.

**Comment by jcansdale** [comment]
> At the time it made sense that if the user selects 0 VsFact/VsTheory tests then no Visual Studio instance should be launched but I can make that work.

That would be great! 👍 

> The only problem with both approaches is that if your package auto loads then you may not be able to debug its Initialization method since it may run before VisualStudioUtil.GetDte finds the DTE instance.

Would this be a problem if you were attaching the debugger from `VsixTesting.ExtensionInstaller`?  E.g.

1. `VsixTesting.ExtensionInstaller` checks to see if the debugger is attached
2. If the debugger is attached, find the parent process ID (there's no managed API for this AFAIK)
3. Find the `DTE` object for the parent process
4. Start the target Visual Studio version
5. Attach the debugger using `DTE.Debugger`

I'm guessing that 5. would happen so early in the launch of `devenv.exe` that it's unlikely that any extension code would have loaded (or even managed code).

**Comment by josetr** [comment]
Forget what I said :smile:, i think the problem is nonexistent in both approaches.
