### ISSUE TITLE
RootSuffix = "" fails with --RootSuffix is required.

### ISSUE THREAD

**Issue by jcansdale** [josetr/VsixTesting#15]
If I mark a test with `[VsTestSettings(RootSuffix = "")]`, it fails with the following exception:

```
Test 'Tests.TestClass.TheoryTest(n: 123) - 2015 ' failed: System.Exception : System.ArgumentException: Argument --RootSuffix is required.
   at VsixTesting.ExtensionInstaller.CommandLineParser.One(String[] args, String name)
   at VsixTesting.ExtensionInstaller.Program.Main(String[] args)
```

The same test passes with, `[VsTestSettings(RootSuffix = "\"\"")]`.

**Comment by josetr** [comment]
This one was one of the "installer improvements" in https://github.com/josetr/VsixTesting/pull/13

https://www.nuget.org/packages/VsixTesting.Xunit/0.1.35-beta 

Please upgrade 👍
