### ISSUE TITLE
Run tests on specific .sln

### ISSUE THREAD

**Issue by Enache-Ionut** [josetr/VsixTesting#25]
Hello,

Can you provide a way to set what SLN  is opened by the devenv.exe? Visual Studio is not initializing an asyncpckage until a solution is opened, thus I cannot run tests on my custom commands.

I saw that you use the following  `VsixTesting.Invoker/Properties/launchSettings.json`, maybe you can add an attribute which can set the path to the solution to open on launch.

**Command line arguments example**: `D:/TestProjects/CustomAllocator.sln /RootSuffix Exp`

**Comment by sharwell** [comment]
@Enache-Ionut for this I would recommend opening the solution as part of the specific test. Is that not a viable solution for you?

**Comment by Enache-Ionut** [comment]
@sharwell it works. Thank you for your time and for creating this really nice nuget package 👍

**Comment by asaf92** [comment]
@sharwell 
How do you open a specific solution? I'm trying to call `IVsSolution2.OpenSolutionFile` but it stays in the welcome screen with the list of previously used projects. I tried `await Task.Delay` for 2 minutes and it didn't change.

**Comment by sharwell** [comment]
I have a bunch of tests for creating a solution, but not sure about opening one that already exists.
https://github.com/dotnet/roslyn-sdk/blob/df51b014fcb8c9e667a0b09a000f2050615f7afb/tests/VisualStudio.Roslyn.SDK/Roslyn.SDK.IntegrationTests/CreateProjectTests.cs
