### ISSUE TITLE
Can't find VsixTesting.dll when the path contains a space

### ISSUE THREAD

**Issue by asaf92** [josetr/VsixTesting#34]
Hi,

When trying to run a test I immediately get a `FileNotFoundException` about VsixTesting.dll.
I used dotPeek to check for the references and found that some DLLs are missing (marked in blue), which might hint to the source of the problem:
![image](https://user-images.githubusercontent.com/35231408/172799225-1b9d710b-2cfd-4f54-a8a3-5ff81d6c0564.png)

I tried running the tests both from VS22 and VS19, targeting different versions for the experimental instance.

**Comment by asaf92** [comment]
OK I found an interesting insight and a workaround:

This fails when the local repo is in a patch that contains a space. The space gets translated to `%20` and the DLL is missing. Moving the same repo to a folder that doesn't have a space in the path solved the issue for me.

**Comment by josetr** [comment]
I've fixed the issue and published a new version on nuget.org.

Thanks for reporting the issue 👍
