### ISSUE TITLE
Version conflict with System.Collections.Immutable

### ISSUE THREAD

**Issue by sharwell** [josetr/VsixTesting#4]
Currently the **VsixTesting.Xunit** package depends indirectly on **System.Collections.Immutable** version 1.4.0. The first version of this package published with Visual Studio is 1.1.36. This mismatch causes warnings during the build if an extension needs to reference System.Collections.Immutable.

📝 The dependency in the test library comes via the reference to Ben.Demystifier. @benaadams in there a version of this package which depends only on System.Collections.Immutable 1.1.36?

**Comment by benaadams** [comment]
https://github.com/benaadams/Ben.Demystifier/blob/master/src/Ben.Demystifier/Ben.Demystifier.csproj
```
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net45</TargetFrameworks>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>key.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning" Version="2.1.17" PrivateAssets="all" />
    <PackageReference Include="SourceLink.Create.CommandLine" Version="2.7.6" PrivateAssets="all" />
    <PackageReference Include="System.Reflection.Metadata">
      <Version>1.5.0</Version>
    </PackageReference>
  </ItemGroup>
```

**Comment by benaadams** [comment]
Not as far as I'm aware; but happy to take advice
