### ISSUE TITLE
ThreadHelper.JoinableTaskFactory is null when running test on Visual Studio 2017

### ISSUE THREAD

**Issue by jcansdale** [josetr/VsixTesting#5]
If I run the following test:
```cs
using Xunit;
using Xunit.Abstractions;
using EnvDTE;
using Microsoft.VisualStudio.Shell;
using Task = System.Threading.Tasks.Task;

namespace VsixTestingTests
{
    public class VsTests
    {
        readonly ITestOutputHelper output;

        public VsTests(ITestOutputHelper output)
        {
            this.output = output;
        }

        [VsFact]
        public async Task VersionAsync()
        {
            await ThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync();
            var dte = (DTE)ServiceProvider.GlobalProvider.GetService(typeof(DTE));
            output.WriteLine(dte.Version);
        }
    }
}
```

It passes on Visual Studio 2015, but `ThreadHelper.JoinableTaskFactory` appears to be null on Visual Studio 2017:
```cs
Output from VsixTestingTests.VsTests.VersionAsync - 2015 Exp:
  14.0
Test 'VsixTestingTests.VsTests.VersionAsync - 2017 Exp' failed: System.NullReferenceException : Object reference not set to an instance of an object.
	at Microsoft.VisualStudio.Shell.ThreadHelper.get_JoinableTaskContext()
	at Microsoft.VisualStudio.Shell.ThreadHelper.get_JoinableTaskFactory()
	Class1.cs(21,0): at VsixTestingTests.VsTests.<VersionAsync>d__2.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

1 passed, 1 failed, 0 skipped, took 34.48 seconds (xUnit.net 2.4.0 build 4049).
```

If I change to `[VsFact(UIThread = true)]`, the test passes on both versions.

Any idea what's going on?

Maybe @AArnott or @jnm2 would have some ideas?

**Comment by AArnott** [comment]
I'm not sure which `[VsFact]` you're using, but if it runs in VS, that's why it would work. I'm surprised the unit testing approach worked in VS 2015 at all. VS 2017 throws NRE when using most functions on ThreadHelper when in a unit test context because certain singleton services haven't been properly initialized as they are in the product.

For now the only advice I can give is that you check out our [testing guidance](https://github.com/Microsoft/vs-threading/blob/master/doc/testing_vs.md). 
Internally, we have a library that sets up all the private fields necessary so that ThreadHelper works properly. I hope we can share that publicly soon.

**Comment by jcansdale** [comment]
@AArnott,

> I'm not sure which [VsFact] you're using, but if it runs in VS, that's why it would work.

It's a new xUnit extension developed by @josetr that runs the unit tests inside a Visual Studio process. The test run is kicked off from the context of a package, see:
https://github.com/josetr/VsixTesting/blob/7fd17fe76abde7babde0c85108d73cd88a2501ca/src/VsixTesting.Invoker/InvokerPackage.cs#L22

I've just noticed this package is compiled against `VSSDK.Shell.11`. If this package is loaded first, is it possible that the singleton services haven't yet been initialized?

I think one possibility would be to read `ThreadHelper.JoinableTaskFactory` from the `Initialize` method of `InvokerPackage`. This would be done using reflection when it detects that it's running on VS 2015/2017. Does this sound like a reasonable approach?

Alternatively, is there a package that initializes these singleton services that could be forced to load before executing any tests?

**Comment by AArnott** [comment]
Any legit VS package will be able to read `ThreadHelper`. If you compile against MPF for that version of VS it should always work. If you compiled against any older version of MPF then it will only work if first accessed from the UI thread.

**Comment by jcansdale** [comment]
This seem to resolve the issue:

```
        protected override void Initialize()
        {
            InitializeThreadHelper();
        }

        private void InitializeThreadHelper()
        {
            if (GetService(typeof(DTE)) is DTE dte)
            {
                var majorVersion = new Version(dte.Version).Major;
                for (var shellVersion = majorVersion; shellVersion >= 14; shellVersion--)
                {
                    var threadHelperTypeName = $"Microsoft.VisualStudio.Shell.ThreadHelper, Microsoft.VisualStudio.Shell.{shellVersion}.0, Version={shellVersion}.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a";
                    var joinableTaskFactoryProperty = Type.GetType(threadHelperTypeName, false)?.GetProperty("JoinableTaskFactory");
                    joinableTaskFactoryProperty?.GetValue(null); // Initialize the JoinableTaskFactory property on the UI thread
                }
            }
        }
```

Do you think it's a reasonable approach?

**Comment by sharwell** [comment]
@AArnott The issue here is each version of Microsoft.VisualStudio.Shell.XX.0.dll is a different assembly and expects to be initialized on the UI thread. One of these assemblies (15.0) is used by built-in Visual Studio packages, and another (11.0) is used by the test harness. That leaves at least two (12.0, 14.0) that are potentially uninitialized when tests start to run. It's not clear to me if older ones (10.0 and earlier) have the same requirement.

**Comment by AArnott** [comment]
Yes, I understand that. What I don't understand is why manually initializing one with one property vs. another would make any difference.

**Comment by jcansdale** [comment]
PR at #6 is ready to merge. Does anyone have any further comments / suggestions? 😄
